Add awstats-update v1.3

diff --git a/usr/local/sbin/awstats-update b/usr/local/sbin/awstats-update
--- a/usr/local/sbin/awstats-update
+++ b/usr/local/sbin/awstats-update
@@ -1,10 +1,10 @@
 #!/bin/bash
-# AWStats Updater 1.2 (build 20140806)
-# Copyright (C) 2011-2014  Daniel Rudolf <www.daniel-rudolf.de>
+# AWStats Updater 1.3 (build 20150508)
+# Copyright (C) 2011-2015  Daniel Rudolf <www.daniel-rudolf.de>
 # 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, either version 3 of the License only.
+# the Free Software Foundation, version 3 of the License only.
 # 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
@@ -15,15 +15,23 @@
 # the GNU General Public License.
 
 APP_NAME="$(basename "$0")"
+EXIT_CODE=0
 
-BUILD="20140806"
-VERSION="1.2"
+BUILD="20150508"
+VERSION="1.3"
 
 # usage
 function showUsage() {
 	echo "Usage:"
 	echo "	$APP_NAME [OPTION]... [--update] [--rebuild|--rebuild-all]"
 }
+
+# include debian config
+AWSTATS_NICE=10
+AWSTATS_LANG="en"
+if [ -r "/etc/default/awstats" ]; then
+	. "/etc/default/awstats"
+fi
 
 # parse options
 WWW_PATH="/var/cache/awstats/www"
@@ -37,16 +45,25 @@ while [ $# -gt 0 ]; do
 			echo "$APP_NAME: Invalid \`--www-path': No path given" >&2
 			showUsage
 			exit 1
-		elif [ ! -e "$2" ]; then
-			echo "$APP_NAME: Invalid \`--www-path': $2: No such file or directory" >&2
-			exit 1
-		elif [ ! -d "$2" ]; then
-			echo "$APP_NAME: Invalid \`--www-path': $2: Not a directory" >&2
-			exit 1
 		fi
 
 		WWW_PATH="$2"
 		shift 2
+
+	elif [ "${1:0:11}" == "--www-path=" ]; then
+		WWW_PATH="${1:11}"
+		if [[ "$WWW_PATH" =~ ^(\".*\"|\'.*\')$ ]]; then
+			let "WWW_PATH_LENGTH = ${#WWW_PATH} - 2"
+			WWW_PATH="${WWW_PATH:1:$WWW_PATH_LENGTH}"
+		fi
+
+		if [ -z "$WWW_PATH" ]; then
+			echo "$APP_NAME: Invalid \`--www-path': No path given" >&2
+			showUsage
+			exit 1
+		fi
+
+		shift
 
 	elif [ "$1" == "--update" ]; then
 		UPDATE="yes"
@@ -102,7 +119,7 @@ while [ $# -gt 0 ]; do
 
 	elif [ "$1" == "--version" ]; then
 		echo "awstats-update $VERSION ($BUILD)"
-		echo "Copyright (C) 2014 Daniel Rudolf"
+		echo "Copyright (C) 2011-2015 Daniel Rudolf"
 		echo "License GPLv3: GNU GPL version 3 only <http://gnu.org/licenses/gpl.html>."
 		echo "This is free software: you are free to change and redistribute it."
 		echo "There is NO WARRANTY, to the extent permitted by law."
@@ -117,16 +134,25 @@ while [ $# -gt 0 ]; do
 	fi
 done
 
+# nothing to do?
+if [ "$UPDATE" == "no" ] && [ "$REBUILD" == "no" ]; then
+	echo "$APP_NAME: You specified \`--no-update' and \`--no-rebuild'; do you really want to do nothing?" >&2
+	exit 1
+fi
+
+# validate www path
+if [ ! -e "$WWW_PATH" ]; then
+	echo "$APP_NAME: Invalid \`--www-path': $WWW_PATH: No such file or directory" >&2
+	exit 1
+elif [ ! -d "$WWW_PATH" ]; then
+	echo "$APP_NAME: Invalid \`--www-path': $WWW_PATH: Not a directory" >&2
+	exit 1
+fi
+
 # you must run this as root
 if [ "$(id -u)" -ne "0" ]; then
 	echo "$APP_NAME: You must run this as \`root'" >&2
 	exit 1
-fi
-
-# nothing to do?
-if [ "$UPDATE" == "no" ] && [ "$REBUILD" == "no" ]; then
-	echo "$APP_NAME: You specified \`--no-update' and \`--no-rebuild'; do you really want to do nothing?" >&2
-	exit
 fi
 
 # prepare fds according to verbosity
@@ -139,12 +165,17 @@ fi
 
 # perform --update
 if [ "$UPDATE" == "yes" ]; then
-	echo "Perform update..."
+	echo "Performing update..."
 
 	IFS=$'\n'; for FILE in /etc/awstats/awstats.*.*.conf; do
+		if [ "$FILE" == "/etc/awstats/awstats.*.*.conf" ]; then
+			echo "$APP_NAME: Unable to perform update: No config files found" >&2
+			exit 1
+		fi
+
 		REGEX="^\/etc\/awstats\/awstats\.([^\.]+)\.(.+)\.conf$"
 		if ! [[ "$FILE" =~ $REGEX ]]; then
-			echo "$APP_NAME: invalid config file \`$FILE'" >&2
+			echo "$APP_NAME: Unable to perform update: Invalid config file \`$FILE'" >&2
 			exit 1
 		fi
 
@@ -154,8 +185,21 @@ if [ "$UPDATE" == "yes" ]; then
 
 		# do it!
 		echo "  - $HOST ($HOST_TYPE)"
-		awstats -config="$HOST_TYPE.$HOST" -update | sed -e 's/^ /  /' | sed -e 's/^/    /' >&4
+		nice -n "$AWSTATS_NICE" \
+			awstats -config="$HOST_TYPE.$HOST" -update \
+				| sed -e 's/^ /  /' | sed -e 's/^/    /' >&4
+		UPDATE_EXIT_CODE=$?
+
+		if [ "$UPDATE_EXIT_CODE" -ne 0 ]; then
+			echo "  ! $HOST ($HOST_TYPE) FAILED with exit code $UPDATE_EXIT_CODE"
+			EXIT_CODE=1
+		fi
 	done
+fi
+
+# check exit code
+if [ "$EXIT_CODE" -ne 0 ]; then
+	exit "$EXIT_CODE"
 fi
 
 # AWStats pages
@@ -164,12 +208,17 @@ PAGES=( main alldomains allhosts lasthosts unknownip allemails lastemails allema
 # perform --rebuild
 if [ "$REBUILD" == "current" ]; then
 	# perform rebuild for the current month
-	echo "Generate static HTML pages..."
+	echo "Generating static HTML pages..."
 
 	IFS=$'\n'; for FILE in /etc/awstats/awstats.*.*.conf; do
+		if [ "$FILE" == "/etc/awstats/awstats.*.*.conf" ]; then
+			echo "$APP_NAME: Unable to generate static HTML pages: No config files found" >&2
+			exit 1
+		fi
+
 		REGEX="^\/etc\/awstats\/awstats\.([^\.]+)\.(.+)\.conf$"
 		if ! [[ "$FILE" =~ $REGEX ]]; then
-			echo "$APP_NAME: invalid config file \`$FILE'" >&2
+			echo "$APP_NAME: Unable to generate static HTML pages: Invalid config file \`$FILE'" >&2
 			exit 1
 		fi
 
@@ -195,6 +244,7 @@ if [ "$REBUILD" == "current" ]; then
 		fi
 
 		# generate static HTML pages
+		REBUILD_EXIT_CODE=0
 		while [ $REBUILD_ROUNDS -gt 0 ]; do
 			# do we have any data?
 			if [ ! -f "/var/lib/awstats/awstats$MONTH$YEAR.$HOST_TYPE.$HOST.txt" ]; then
@@ -223,6 +273,7 @@ if [ "$REBUILD" == "current" ]; then
 				[ "$VERBOSE" -eq 2 ] && echo -n "$YEAR-$MONTH " >&3
 
 				# generate static HTML pages
+				ROUND_EXIT_CODE=0
 				PAGE_INDEX=0
 				PAGE_COUNT=${#PAGES[@]}
 				while [ $PAGE_INDEX -lt $PAGE_COUNT ]; do
@@ -231,16 +282,27 @@ if [ "$REBUILD" == "current" ]; then
 
 					echo -n "$PAGE " >&4
 
-					awstats -config="$HOST_TYPE.$HOST" -update \
-						-output="$PAGE" -year="$YEAR" -month="$MONTH" \
-						-staticlinks -lang="de" \
-					> "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH/awstats.$HOST_TYPE.$HOST.$PAGE.html"
+					nice -n "$AWSTATS_NICE" \
+						awstats -config="$HOST_TYPE.$HOST" -update \
+							-output="$PAGE" -year="$YEAR" -month="$MONTH" \
+							-staticlinks -lang="$AWSTATS_LANG" \
+						> "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH/awstats.$HOST_TYPE.$HOST.$PAGE.html"
+					PAGE_EXIT_CODE=$?
+
+					if [ "$PAGE_EXIT_CODE" -ne 0 ]; then
+						echo -n "[FAILED with exit code $PAGE_EXIT_CODE] " >&4
+						ROUND_EXIT_CODE=1
+						REBUILD_EXIT_CODE=1
+						EXIT_CODE=1
+					fi
 				done
 
 				# symlink index.html
 				ln -s "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH/awstats.$HOST_TYPE.$HOST.main.html" "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH/index.html"
 
 				echo "" >&4
+				[ "$ROUND_EXIT_CODE" -ne 0 ] && echo "    ! $YEAR-$MONTH FAILED" >&4
+				[ "$ROUND_EXIT_CODE" -ne 0 ] && [ "$VERBOSE" -eq 2 ] && echo -n "[FAILED] " >&3
 			fi
 
 			# prepare next rebuild round
@@ -257,21 +319,26 @@ if [ "$REBUILD" == "current" ]; then
 		done
 
 		[ "$VERBOSE" -eq 2 ] && echo "" >&3
+		[ "$REBUILD_EXIT_CODE" -ne 0 ] && echo "  ! $HOST ($HOST_TYPE) FAILED"
 	done
-fi
 
 # perform --rebuild-all
-if [ "$REBUILD" == "all" ]; then
+elif [ "$REBUILD" == "all" ]; then
 	# collect rebuild data
 	# actually this wouldn't be necessary, but AWStats database files aren't sorted at all
 	# this is just for the sake of a nicer output...
-	echo "Collect rebuild data..."
+	echo "Collecting rebuild data..."
 
 	REBUILD_DATA=""
 	IFS=$'\n'; for FILE in /var/lib/awstats/awstats*.*.*.txt; do
+		if [ "$FILE" == "/var/lib/awstats/awstats*.*.*.txt" ]; then
+			echo "$APP_NAME: Unable to collect rebuild data: No database files found" >&2
+			exit 1
+		fi
+
 		REGEX="^\/var\/lib\/awstats\/awstats([0-9]{2})([0-9]{4})\.([^\.]+)\.(.+)\.txt$"
 		if ! [[ "$FILE" =~ $REGEX ]]; then
-			echo "$APP_NAME: invalid database file \`$FILE'" >&2
+			echo "$APP_NAME: Unable to collect rebuild data: Invalid database file \`$FILE'" >&2
 			exit 1
 		fi
 
@@ -287,9 +354,12 @@ if [ "$REBUILD" == "all" ]; then
 	REBUILD_DATA="$(echo "$REBUILD_DATA" | LC_ALL=C sort)"
 
 	# perform rebuild...
-	echo "Generate static HTML pages..."
+	echo "Generating static HTML pages..."
 
+	REBUILD_EXIT_CODE=0
+	PREVIOUS_HOST_TYPE=""
 	PREVIOUS_HOST=""
+	IGNORE_HOST_TYPE=""
 	IGNORE_HOST=""
 	IFS=$'\n'; for DATA in $REBUILD_DATA; do
 		HOST_TYPE="$(echo "$DATA" | cut -d '/' -f 1)"
@@ -299,25 +369,37 @@ if [ "$REBUILD" == "all" ]; then
 		MONTH="$(echo "$DATA" | cut -d '/' -f 4)"
 
 		# something is wrong with this host; ignore it!
-		if [ "$IGNORE_HOST" == "$HOST_TYPE/$HOST" ]; then
+		if [ "$IGNORE_HOST_TYPE" == "$HOST_TYPE" ] && [ "$IGNORE_HOST" == "$HOST" ]; then
 			continue
 		fi
 
 		# new host
-		if [ "$PREVIOUS_HOST" != "$HOST_TYPE/$HOST" ]; then
-			[ -n "$PREVIOUS_HOST" ] && [ "$VERBOSE" -eq 2 ] && echo "" >&3
+		if [ "$PREVIOUS_HOST_TYPE" != "$HOST_TYPE" ] || [ "$PREVIOUS_HOST" != "$HOST" ]; then
+			if [ -n "$PREVIOUS_HOST" ] && [ "$VERBOSE" -eq 2 ]; then
+				if [ "$PREVIOUS_HOST_TYPE" != "$IGNORE_HOST_TYPE" ] || [ "$PREVIOUS_HOST" != "$IGNORE_HOST" ]; then
+					echo "" >&3
+				fi
+			fi
 
-			PREVIOUS_HOST="$HOST_TYPE/$HOST"
+			[ "$REBUILD_EXIT_CODE" -ne 0 ] && echo "  ! $PREVIOUS_HOST ($PREVIOUS_HOST_TYPE) FAILED"
+			REBUILD_EXIT_CODE=0
+
+			PREVIOUS_HOST_TYPE="$HOST_TYPE"
+			PREVIOUS_HOST="$HOST"
+
+			# check for AWStats config file
+			if [ ! -f "/etc/awstats/awstats.$HOST_TYPE.$HOST.conf" ]; then
+				echo "  - $HOST ($HOST_TYPE): config file not found; skipping..."
+				IGNORE_HOST_TYPE="$HOST_TYPE"
+				IGNORE_HOST="$HOST"
+				continue
+			fi
+
+			# print current host
 			if [ "$VERBOSE" -eq 2 ]; then
 				echo -n "  - $HOST ($HOST_TYPE): " >&3
 			else
 				echo "  - $HOST ($HOST_TYPE)"
-			fi
-
-			# check for AWStats config file
-			if [ ! -f "/etc/awstats/awstats.$HOST_TYPE.$HOST.conf" ]; then
-				echo "$APP_NAME: database files exist for host $HOST ($HOST_TYPE), but no config file; skipping..." >&2
-				continue
 			fi
 		fi
 
@@ -343,6 +425,7 @@ if [ "$REBUILD" == "all" ]; then
 		[ "$VERBOSE" -eq 2 ] && echo -n "$YEAR-$MONTH " >&3
 
 		# generate static HTML pages
+		ROUND_EXIT_CODE=0
 		PAGE_INDEX=0
 		PAGE_COUNT=${#PAGES[@]}
 		while [ $PAGE_INDEX -lt $PAGE_COUNT ]; do
@@ -351,20 +434,36 @@ if [ "$REBUILD" == "all" ]; then
 
 			echo -n "$PAGE " >&4
 
-			awstats -config="$HOST_TYPE.$HOST" -update \
-				-output="$PAGE" -year="$YEAR" -month="$MONTH" \
-				-staticlinks -lang="de" \
-			> "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH/awstats.$HOST_TYPE.$HOST.$PAGE.html"
+			nice -n "$AWSTATS_NICE" \
+				awstats -config="$HOST_TYPE.$HOST" -update \
+					-output="$PAGE" -year="$YEAR" -month="$MONTH" \
+					-staticlinks -lang="$AWSTATS_LANG" \
+				> "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH/awstats.$HOST_TYPE.$HOST.$PAGE.html"
+			PAGE_EXIT_CODE=$?
+
+			if [ "$PAGE_EXIT_CODE" -ne 0 ]; then
+				echo -n "[FAILED with exit code $PAGE_EXIT_CODE] " >&4
+				ROUND_EXIT_CODE=1
+				REBUILD_EXIT_CODE=1
+				EXIT_CODE=1
+			fi
 		done
 
 		# symlink index.html
 		ln -s "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH/awstats.$HOST_TYPE.$HOST.main.html" "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH/index.html"
 
 		echo "" >&4
+		[ "$ROUND_EXIT_CODE" -ne 0 ] && echo "    ! $YEAR-$MONTH FAILED" >&4
+		[ "$ROUND_EXIT_CODE" -ne 0 ] && [ "$VERBOSE" -eq 2 ] && echo -n "[FAILED] " >&3
 	done
+
+	[ -n "$PREVIOUS_HOST" ] && [ "$VERBOSE" -eq 2 ] && echo "" >&3
+	[ "$REBUILD_EXIT_CODE" -ne 0 ] && echo "  ! $HOST ($HOST_TYPE) FAILED"
 fi
 
 # clean up
 exec 3>&-
 exec 4>&-
-exit 0
+
+# exit
+exit "$EXIT_CODE"
